backend:
  name: github
  repo: khaleeqrehman/portfolio-v2  # Format: your-username/repo-name
  branch: main                      # Default branch (main/master)
  # auth_type: implicit             # Uncomment only if using GitHub Enterprise

# Media storage
media_folder: "static/images/uploads"  # Where uploaded images are saved
public_folder: "/images/uploads"       # Public URL path for images

# Collections (blog posts)
collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"         # Path to your markdown files
    create: true                    # Allow creating new posts
    slug: "{{slug}}"                # Auto-generate filenames
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD" }
      - { label: "Body", name: "body", widget: "markdown" }